language: go
go: 1.10.x
env:
  global:
    - CGO_ENABLED: 0
matrix:
  fast_finish: true
install:
  - go get -t ./...
script:
  - go test -v ./...
jobs:
  include:
    - {os: linux, dist: trusty, sudo: required}
    - {os: osx, osx_image: xcode8.3}
    - {os: osx, osx_image: xcode9.3}
   